"""Add quality_score to FaceEncoding

Revision ID: 76ee7cb01cd4
Revises: 3551e462f2da
Create Date: 2026-03-06 23:51:39.268043

"""
from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision = '76ee7cb01cd4'
down_revision = '3551e462f2da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('face_encodings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quality_score', sa.Float(), nullable=False, server_default='0.0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('face_encodings', schema=None) as batch_op:
        batch_op.drop_column('quality_score')

    # ### end Alembic commands ###
