"""Add image_filename to FaceEncoding

Revision ID: ff5298c346cc
Revises: 76ee7cb01cd4
Create Date: 2026-03-07 00:44:03.315078

"""
from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision = 'ff5298c346cc'
down_revision = '76ee7cb01cd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('face_encodings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('face_encodings', schema=None) as batch_op:
        batch_op.drop_column('image_filename')

    # ### end Alembic commands ###
